# Generated by Django 4.2.29 on 2026-06-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_watchlist_wachhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wachhistory',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='wachhistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
