# Generated by Django 4.2.29 on 2026-06-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_movie_id_wachhistory_movie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WachHistory',
            new_name='WacthHistory',
        ),
    ]
