# Generated by Django 4.2.29 on 2026-06-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_wachhistory_wacthhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WacthHistory',
            new_name='WatchHistory',
        ),
    ]
